// ProjectFile model representing a file in a project workspace
// This model stores metadata and content for each file generated by the AI Coding Agent.

import mongoose from 'mongoose';

const ProjectFileSchema = new mongoose.Schema(
  {
    project: { type: mongoose.Schema.Types.ObjectId, ref: 'Project', required: true },
    path: { type: String, required: true }, // full path relative to the project root
    name: { type: String, required: true },
    extension: { type: String, required: true },
    content: { type: String, default: '' },
    language: { type: String, required: true }, // e.g., 'javascript', 'typescript', 'python'
    version: { type: Number, default: 1 }, // incremented on each update
    createdBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
    createdAt: { type: Date, default: Date.now },
    updatedAt: { type: Date, default: Date.now }
  },
  {
    // Enable mongoose's built‑in timestamps (updates updatedAt automatically)
    timestamps: { createdAt: 'createdAt', updatedAt: 'updatedAt' }
  }
);

// Middleware to bump version on each save (except initial creation)
ProjectFileSchema.pre('save', function (next) {
  if (!this.isNew) {
    this.version += 1;
  }
  next();
});

export default mongoose.model('ProjectFile', ProjectFileSchema);
